### ISSUE TITLE
希望能增加自定义post header和body的输入框

### ISSUE THREAD

**Issue by xiebruce** [yuki-xin/picgo-plugin-web-uploader#2]
因为我的自定义接口服务器用nginx做了basic http认证，上传的时候需要在header里添加一个 authorization: basic xxxxxxxx== 这样的header。同时body也有可能有这个需求，其实参照mweb自定义服务器即可：
![image](https://user-images.githubusercontent.com/13575500/56866940-f5108680-6a11-11e9-8d45-339e630b1023.png)

**Comment by yuki-xin** [comment]
fixed
