### ISSUE TITLE
Chevereto图床一直设置不正确哦，希望能有更详细的教程

### ISSUE THREAD

**Issue by wojinkuangzhan** [yuki-xin/picgo-plugin-web-uploader#3]
Chevereto图床一直设置不正确哦，希望能有更详细的教程

**Comment by wojinkuangzhan** [comment]
> Chevereto图床一直设置不正确哦，希望能有更详细的教程

**Comment by yuki-xin** [comment]
先通过Restful工具把服务端接口调通，两点:
1. 能通过formdata方式将文件post到后端服务器
2. 能获得JSON格式的返回值

再讲调用接口的参数填入插件选项即可

**Comment by hqyyqh** [comment]
按照 [chevereto](https://chevereto.com/docs/api-v1) 的接口说明
尝试了如下配置
```json
url: http://mysite.com/api/1/upload
paramName: source
jsonPath: data.url
customHeader: {"key":"my_api_key","format":"redirect"}
```
没有成功上传，查过很多资料都没有成功。chevereto 是个很好的图床，希望能有一些配置说明。

相关参考资料：
[SM.MS 图床配合 PicGo 使用二](http://elmagnifico.me/2019/08/30/SMMS-PicGos2/)
[Atom 插件开发 - 使用自己的 Chevereto 图床 API](https://juejin.im/post/5ae436926fb9a07a9f014e45)

**Comment by yuki-xin** [comment]
> 按照 [chevereto](https://chevereto.com/docs/api-v1) 的接口说明
> 尝试了如下配置
> 
> ```json
> url: http://mysite.com/api/1/upload
> paramName: source
> jsonPath: data.url
> customHeader: {"key":"my_api_key","format":"redirect"}
> ```
> 
> 没有成功上传，查过很多资料都没有成功。chevereto 是个很好的图床，希望能有一些配置说明。
> 
> 相关参考资料：
> [SM.MS 图床配合 PicGo 使用二](http://elmagnifico.me/2019/08/30/SMMS-PicGos2/)
> [Atom 插件开发 - 使用自己的 Chevereto 图床 API](https://juejin.im/post/5ae436926fb9a07a9f014e45)

貌似chevereto的参数是提交到form中，目前未开放自定义body

**Comment by yuki-xin** [comment]
@hqyyqh  使用1.1.0版本的插件，有customBody的插件

`url` :  http://your-site/api/1/upload
`paramName`: source
`jsonPath`: image.url
`customBody`:  {"key":"youkey"}

**Comment by hqyyqh** [comment]
> @hqyyqh 使用 1.1.0 版本的插件，有 customBody 的参数
> 
> `url` : http://your-site/api/1/upload
> `paramName`: source
> `jsonPath`: image.url
> `customBody`: {"key":"youkey"}

太感谢了，成功上传。
